name: Code Quality Check

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - dev

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.py
            !**/migrations/*
          DOT: '...'
          DIFF_FILTER: 'AMRC'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort flake8 pydocstyle

      - name: Run isort on changed files
        run: isort ${{ env.GIT_DIFF }}
        if: env.GIT_DIFF

      - name: Run flake8 on changed files
        run: flake8 ${{ env.GIT_DIFF }}
        if: env.GIT_DIFF

      - name: Run pydocstyle on changed files
        run: pydocstyle ${{ env.GIT_DIFF }}
        if: env.GIT_DIFF
